export const RECENT_TRADES_CONTAINER_HEIGHT_MIN = 350
export const RECENT_TRADES_CONTAINER_HEIGHT_MAX = 570

export const TRADES_LIST_MINI_CONTAINER_HEIGHT_MAX = 40

export const TRADES_LIST_MINI_MAX_ELEMENTS = 15
