export const RECENT_TRADES_CONTAINER_HEIGHT_MIN = 300
export const RECENT_TRADES_CONTAINER_HEIGHT_MAX = 420

export const TRADES_LIST_MINI_CONTAINER_HEIGHT_MAX = 40

export const TRADES_LIST_MINI_MAX_ELEMENTS = 15

export const RECENT_TRADES_POLLING_INTERVAL_MS = 1000
