export const RECENT_TRADES_CONTAINER_HEIGHT_MIN = 370
export const RECENT_TRADES_CONTAINER_HEIGHT_MAX = 510

export const TRADES_LIST_HORIZONTAL_CONTAINER_HEIGHT_MAX = 40

export const TRADES_LIST_HORIZONTAL_MAX_ELEMENTS = 10
